### ISSUE TITLE
Remarks

### ISSUE THREAD

**Issue by JohnKhandygo** [DeKinci/PolyProjects2#1]
Должен сказать, что код в очень неплохом состоянии! Тем не менее, есть несколько замечаний:

- [ ] В настоящее время checked exceptions считаются плохим стилем (Вы могли заметить, например, что в Kotlin'е их нет) (можно найти много информации на эту тему, см. например [здесь](https://blog.philipphauer.de/checked-exceptions-are-evil/)).
- [ ] Очень странно видеть, что методы `get` бросают исключения. В таких ситуациях, как правило, нет ничего исключительного. Представьте, если бы `Map` бросал исключение каждый раз, когда Вы спрашиваете у него несуществующий ключ. 
- [ ] Это, конечно, очень хорошо, что Вы описали поведение методов `changePrice`, `renameProduct` и `delete` в случае несуществующего продукта, однако с точки зрения программиста, работающего с Вашей разработкой, нет никакой возможности узнать, произошло ли на самом деле изменение/удаление. Это иногда бывает полезным. Хорошим примером здесь снова может быть `Map` (см. методы `remove` и `replace`). 
- [ ] Класс `PriceList` хранит изменяемое состояние, которое небезопасно при работе из нескольких потоков. 
- [ ] Не понятно, почему `PriceList` является параметризуемым классом. В этом точно есть необходимость?

**Comment by DeKinci** [comment]
- [x] `IllegalArgumentException` наследуются от `RuntimeException` и не является checked exception. То, что он оказался вынесен в объявление метода - скорее оплошность (изначально это был интерфейс, и хотелось указать, почему и в каких случаях кидать исключение, но потом я переписал его с параметрами).
- [x] Запрос товара с неверным id, является в данном случае ошибкой в разработке программы с использованием этого класса. Если вернется null, то у разработчика, вероятно, произойдет NPE (или ему придется каждый раз проверять это), что принципиально ничего не меняет, но дает мне возможность указать причину в сообщении исключения, и упрощает отладку тому, кто допустил ошибку.
- [ ] Принял к сведению. Если мои аргументы про исключения достаточно убедительны, то добавлю бросание исключения (как сперва и хотел), если нет - буду возвращать boolean.
- [ ] Многопоточность совершенно не учитывалась при разработке этого класса, ведь, например, используется обычный HashMap. Если есть необходимость, могу переписать свой класс "с volatile и блокировками".
- [x] Параметризация дает возможность сделать различные прайс-листы для различных типов продуктов и не волноваться о случайном добавлении помидоров в "товары для дома". Как можно заметить, возможные параметры ограничены реализовывателями (наследниками) `Product`, так что это лишь расширение функционала. Тем более, у некоторых типов продуктов могут быть дополнительные методы, например "getCharacteristics", и такой подход может спасти от постоянной необходимости преобразовывать типы.

**Comment by DeKinci** [comment]
[x] Хорошо, исправлю на null. Из-за параметризации null object потребует рефлексии. Хотя, так даже интереснее...
[x] Взято в кавычки, чтобы напоминать известную фразу Бендера. Они там действительно не нужны. Внести изменения?

**Comment by JohnKhandygo** [comment]
- Чем Вам `Optional` не угодил?
- Да, конечно.

**Comment by DeKinci** [comment]
-[x] Ок
-[x] Ок

**Comment by DeKinci** [comment]
@JohnKhandygo добавить тесты на многопоточность или не надо?

**Comment by DeKinci** [comment]
Если нужны - откройте новый issue
