### ISSUE TITLE
Next pls!

### ISSUE THREAD

**Issue by DeKinci** [DeKinci/PolyProjects2#2]
Если нет замечаний, то дайте следующий проект, пожалуйста

**Comment by JohnKhandygo** [comment]
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**Задача:**

Вывод содержимого указанной в качестве аргумента директории в виде отсортированного списка имен файлов.
Флаг -l (long) переключает вывод в длинный формат, в котором, кроме имени файла, указываются права на выполнение/чтение/запись в виде битовой маски XXX, время последней модификации и размер в байтах.
Флаг -h (human-readable) переключает вывод в человеко-читаемый формат (размер в кило-, мега- или гигабайтах, права на выполнение в виде rwx).
Флаг -r (reverse) меняет порядок вывода на противоположный.
Флаг -o (output) указывает имя файла, в который следует вывести результат; если этот флаг отсутствует, результат выводится в консоль.
В случае, если в качестве аргумента указан файл, а не директория, следует вывести информацию об этом файле.

Command Line: ls [-l] [-h] [-r] [-o output.file] directory_or_file

Кроме самой программы, следует написать автоматические тесты к ней.

**Comment by DeKinci** [comment]
>отсортированного списка 
По алфавиту сортировать?
Или по всякому?

**Comment by JohnKhandygo** [comment]
Давайте по всякому. Итак достаточно простая задача. Типа по алфавиту, по размеру, по дате создания или модификации. На каждый тип сортировки заведите свой флаг, при этом применение нескольких сортировок должно учитывать порядок передачи флагов.
